backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "config"
    label: "Ajustes del Sitio"
    delete: false # Evitar borrar el archivo de configuración
    editor:
      preview: false
    files:
      - name: "general"
        label: "Configuración General"
        file: "src/content/config/general.json"
        description: "Logo, Galería y otras imágenes globales"
        fields:
          - { label: "Logo del Bar", name: "logo", widget: "image", required: false }
          - { label: "Nombre del Bar", name: "siteName", widget: "string" }
          - { label: "Imagen Hero de fondo", name: "heroImage", widget: "image" }
          - label: "Galería de Imágenes"
            name: "gallery"
            widget: "list"
            fields:
              - { label: "Título", name: "label", widget: "string" }
              - { label: "Imagen", name: "image", widget: "image" }

  - name: "carta"
    label: "Carta"
    folder: "src/content/carta"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre del plato/bebida", name: "title", widget: "string" }
      - { label: "Ingredientes / Descripción", name: "description", widget: "text", required: false }
      - { label: "Precio", name: "price", widget: "number", value_type: "float" }
      - { 
          label: "Categoría", 
          name: "category", 
          widget: "select", 
          options: ['Para Picar', 'Raciones', 'Bebidas', 'Postres'] 
        }
